USE sakila;

-- Effettuate un’esplorazione preliminare del database. Di cosa si tratta? Quante e quali tabelle contiene? 
-- Fate in modo di avere un’idea abbastanza chiara riguardo a con cosa state lavorando.

SHOW TABLES ;

-- calcola il numero totale delle tabelle
SELECT COUNT(*) AS total_tables
FROM   information_schema.tables
WHERE  table_schema = 'sakila';
  
-- elenca tutte le tabelle per nome
  
SELECT  table_name  
FROM   information_schema.tables
WHERE  table_schema = 'sakila';

-- Scoprite quanti clienti si sono registrati nel 2006.

SELECT COUNT(*) AS CONTEGGIO
FROM CUSTOMER 
WHERE CREATE_DATE BETWEEN '2006-01-01' AND '2006-12-31' ;

SELECT COUNT(*) AS CONTEGGIO
FROM CUSTOMER 
WHERE YEAR(CREATE_DATE) = '2006';

-- Trovate il numero totale di noleggi effettuati il giorno 1/1/2006.

SELECT DISTINCT COUNT(*) AS TOTALE_NOLEGGI
FROM RENTAL
WHERE DATE(RENTAL_DATE) = '2006-01-01' ;

-- Elencate tutti i film noleggiati nell’ultima settimana e tutte le informazioni legate al cliente che li ha noleggiati.

SELECT FILM.TITLE AS NOME_FILM, CONCAT(CUSTOMER.FIRST_NAME, " ", CUSTOMER.LAST_NAME) AS NOME_COGNOME , RENTAL.RENTAL_DATE AS DATA_NOLEGGIO
FROM RENTAL
JOIN INVENTORY ON RENTAL.INVENTORY_ID= INVENTORY.INVENTORY_ID 
JOIN FILM ON FILM.FILM_ID = INVENTORY.FILM_ID
JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID = RENTAL.CUSTOMER_ID
WHERE
    RENTAL.RENTAL_DATE >= (SELECT DATE_SUB(MAX(rental_date), INTERVAL 1 WEEK) FROM rental);
 
 -- Calcolate la durata media del noleggio per ogni categoria di film. DA RIVEDERE
 
 SELECT CATEGORY.NAME AS CATEGORIA,  AVG (DATEDIFF(DATE, RENTAL_DATE, RETURN_DATE)) AS MEDIA_NOLEGGIO
 FROM CATEGORY
 JOIN FILM_CATEGORY ON FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID
 JOIN FILM ON FILM.FILM_ID =FILM_CATEGORY.FILM_ID
 JOIN INVENTORY ON INVENTORY.FILM_ID = FILM.FILM_ID
 JOIN RENTAL ON RENTAL.RENTAL_ID = INVENTORY.RENTAL_ID
 GROUP BY CATEGORY.NAME ;
 
 SELECT CATEGORY.NAME AS CATEGORIA, AVG(FILM.RENTAL_DURATION) AS MEDIA_DURATA_NOLEGGIO
FROM CATEGORY
JOIN FILM_CATEGORY ON FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID
JOIN FILM ON FILM.FILM_ID = FILM_CATEGORY.FILM_ID
GROUP BY CATEGORY.NAME;

--  TROVATE LA DURATA DEL NOLEGGIO PIU LUNGO

SELECT MAX(DATEDIFF( RENTAL.RETURN_DATE, RENTAL.RENTAL_DATE)) AS DURATA_NOLEGGIO_MAX
FROM RENTAL ;
